### PR TITLE
Fixed syntax and removed special char in tool_name.

### LINKED ISSUE #4: cb-boutiques: protect tool names from '-' and other special characters.

### PR DESCRIPTION
**Pull request by natacha-beck**
Maybe I'm to conservative...

fixes #4

### CODE REVIEW

File: lib-ruby/tool_creator.rb [hunk 1]
```diff
@@ -24,17 +24,17 @@
...
-    [cbrain_tool_name, cbrain_tool_name+"/portal",cbrain_tool_name+"/bourreau", cbrain_tool_name+"/views"].each do |dir|
+    [cbrain_tool_name, "#{cbrain_tool_name}/portal", "#{cbrain_tool_name}/bourreau", "#{cbrain_tool_name}/views"].each do |dir|
       Dir.mkdir(dir) unless Dir.exists?(dir)
     end
 
-    portal_name    = cbrain_tool_name + "/portal/"+cbrain_tool_name+".rb"
-    bourreau_name  = cbrain_tool_name + "/bourreau/"+cbrain_tool_name+".rb"
-    view_show_name = cbrain_tool_name + "/views/_show_params.html.erb"
-    view_task_name = cbrain_tool_name + "/views/_task_params.html.erb"
+    portal_name    = "#{cbrain_tool_name}/portal/#{brain_tool_name}.rb"
```
Comment (glatard) [inline lib-ruby/tool_creator.rb]: Typo: brain_tool_name -> cbrain_tool_name.

**Comment by natacha-beck** [comment]
Sorry should be ok now.
